"""fix profile

Revision ID: a405f22712fd
Revises: e7a0baf5237b
Create Date: 2026-04-04 15:38:42.077996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a405f22712fd'
down_revision: Union[str, None] = 'e7a0baf5237b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('author_profiles_metrics_id_fkey', 'author_profiles', type_='foreignkey')
    op.drop_column('author_profiles', 'metrics_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_profiles', sa.Column('metrics_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('author_profiles_metrics_id_fkey', 'author_profiles', 'profile_metrics', ['metrics_id'], ['id'])
    # ### end Alembic commands ###
