"""add texts

Revision ID: e9ad06493f25
Revises: c0823484ddd6
Create Date: 2026-04-04 15:26:00.573200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ad06493f25'
down_revision: Union[str, None] = 'c0823484ddd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_profiles', sa.Column('metrics_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'author_profiles', 'profile_metrics', ['metrics_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_profiles', type_='foreignkey')
    op.drop_column('author_profiles', 'metrics_id')
    # ### end Alembic commands ###
